### ISSUE TITLE
Authorization error: Unauthorized access to URL

### ISSUE THREAD

**Issue by felipecruz91** [umbraco/Umbraco-CMS#10671]
First of all, I'd like to publicly appreciate all the hard work the Umbraco team is doing with regards to Umbraco 9!

### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

After doing a fresh Umbraco installation, I get redirected to the Umbraco back-office and a popup error is displayed:

```
Authorization error: Unauthorized access to URL:
/umbraco/backoffice/umbracoapi/content/AllowsCultureVariation
Contact your administrator for information.
```

### Specifics

Dockerfile:

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY *.sln ./

RUN dotnet nuget add source "https://www.myget.org/F/umbracoprereleases/api/v3/index.json" -n "Umbraco Prereleases"

COPY src/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p src/${file%.*}/ && mv $file src/${file%.*}/; done

RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet build -c Release -o ./out/build

FROM build-env AS publish
RUN dotnet publish -c Release -o ./out/publish --no-restore

COPY ./src/DemoStore.Web/umbraco ./out/publish/umbraco

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:80
COPY --from=publish /app/out/publish ./

ENTRYPOINT ["dotnet", "DemoStore.Web.dll"]
```

Docker compose file:

```
version: '3'

services:
  umbraco-db:
    container_name: umbraco-db-mssql-2017
    image: mcr.microsoft.com/mssql/server:2017-latest
    env_file: ./configs/ms.sql.env
    networks:
      - umbraco-network
    volumes:
      - umbraco.db:/var/opt/mssql/data
    restart: always
    ports:
      - '3930:1433'
      - '3931:1434'
  
  umbraco-netcore:
    restart: always
    links:
      - umbraco-db:umbraco-db
    depends_on:
      - umbraco-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - umbraco-network

volumes:
  umbraco.db:

networks:
  umbraco-network: null
```

### Steps to reproduce

1. Install Umbraco 9.0.0-rc001 following the instructions [here](https://umbraco.com/blog/umbraco-9-release-candidate/) and running it with docker-compose afterwards.

2. Once installation is completed, I get redirected to http://localhost:8080/umbraco/#/content and the following error is shown:

![image](https://user-images.githubusercontent.com/15997951/125502051-e934e82a-74aa-42dc-bb6a-a2b125d1ec82.png)

### Expected result / actual result

I'd expect not to see any errors after the installation.
