### ISSUE TITLE
Umbraco doesnt look for app_plugins outside of wwwroot on linux

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#11030]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9

### Bug summary

That error occured when successfully deployed to linux webapp, and in time of debugging noticedall searchable paths were prefix with wwwroot and it happens only on linux. To make that more interesting it is actually picking up manifest, but all js/css files are not loaded as path is on linux with wwwroot

### Steps to reproduce

Deploy umbraco to linux webapp and noticed anything what use app_plugins is not load

**Comment by Zeegaan** [comment]
Hello there! Thank for your bug report ! 🐛 

I sadly can't seem to replicate this bug, could you specify a smaller test with some reproduciple steps for me? 🕵️ 

# How i tested this:
- Installed the rc-002 template
- Created the App_Plugins folder and put some pictures in there
- Publish rc-002 template to a linux webapp
- I opened up advanced tools in azure & navigated to the published folder
![image](https://user-images.githubusercontent.com/70372949/132354303-0449fb92-f572-45c7-bb4b-c31192c4c82b.png)
- The App_Plugins folder was there
- Checked if there was files in the folder 
![image](https://user-images.githubusercontent.com/70372949/132354527-ecbed752-4763-4328-8146-a1cf2d767cb8.png)
- Tried using the backoffice, created a empty document type with a template
- Tried using a <image> with src in the App_Plugins folder
![image](https://user-images.githubusercontent.com/70372949/132354651-67576a1c-412f-4aae-b69d-ccd0f2bd1f75.png)
![image](https://user-images.githubusercontent.com/70372949/132354738-e0c9850f-f0ba-4df9-996d-e0e4a81efabf.png)

Please tell me if i missed something, and thanks again for the report 💯

**Comment by Zeegaan** [comment]
Hello again! Thank you for the clarification it helped alot with the detective work🕵️ 

I tried installing the rc-002 template & uSync and then pushed it to my linux webapp and i had some issues like you said!

It seems that when i publish with visual studio, it doesn't run the build for some reason on the webapp, and therefore the files didn't get uploaded. 

I solved this by publishing to a folder, and then in VS Code publishing that folder to my linux webapp, and that worked! 💪 
I honestly have no idea why visual studio publishing doesn't work 😢

Here are the steps i followed to get it to work though: 

- Install the Umbraco-rc002 template
- Add uSync with `dotnet add package uSync`
- Publish the project to a folder
- Open that folder with VS Code
- Publish to Azure AppService with VS Code

My App_Plugins folder: 
![image](https://user-images.githubusercontent.com/70372949/132471491-d2d1c05d-7bb3-497f-b055-08a3713bb003.png)

My uSync dashboard: 
![image](https://user-images.githubusercontent.com/70372949/132471768-4b396f2a-28fc-4e9a-adb0-ce5841efb3ba.png)

**Comment by bielu** [comment]
hmmm for me app_plugins was deployed to webapp, but wasn't loading and I am using actually donet cli through devops not visual studio :) example pipeline:
```
parameters:
- name: PoolName
  type: string
  default: 'Default'
- name: projectName
  type: string
  default: 'project'
- name: solution
  type: string
  default: '**/*.sln'
- name: buildPlatform
  type: string
  default: 'Any CPU'
- name: buildConfiguration
  type: string
  default: 'Release'
- name: environment
  type: string
  default: 'development'
- name: subscription
  type: string
  default: 'mySubscription'
- name: webappName
  type: string
  default: 'myWebapp'
stages:
  - stage: buildBE
    displayName: Build Backend
    jobs:
    - job: Build
      pool: 
        name: '${{parameters.PoolName}}'
        demands:
          Agent.OS -equals Linux
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
          packageType: sdk
          version: 5.0.400
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          feedsToUse: 'config'
          projects: '**/*.csproj'
          nugetConfigPath: '$(System.DefaultWorkingDirectory)/DevOps/NuGetCI.Config'
      - task: NodeTool@0  
        displayName: Use node >=12.0.0
        inputs:
          versionSpec: '>=12.0.0'
          checkLatest: true

      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          workingDirectory: '$(System.DefaultWorkingDirectory)/src'
          packDirectory: '$(build.ArtifactStagingDirectory)'
          arguments: '--configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true
          modifyOutputPath: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: 'publish artifacts'
          publishLocation: 'Container'
  - stage: ${{parameters.environment}}
    displayName: Deploy Backend ${{parameters.environment}}
    variables:
      Release.EnvironmentName: ${{parameters.environment}}
    jobs:
    - job: Deploybackend
      displayName: Deploy Backend
      pool: 
        name: '${{parameters.PoolName}}'
        demands:
          Agent.OS -equals Windows_NT
      steps:
      - download: current
        artifact: 'publish artifacts'
      - task: FileTransform@1
        inputs:
          folderPath: '$(Pipeline.Workspace)/publish artifacts/**/*.zip'
          fileType: 'json'
          targetFiles: |
            **/appsettings.json
            **/appsettings.*.json
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: '${{parameters.subscription}}'
          appType: 'webAppLinux'
          WebAppName: '${{parameters.webappName}}'
          packageForLinux: '$(Pipeline.Workspace)/publish artifacts/**/*.zip'
          enableXmlTransform: true
          enableXmlVariableSubstitution: true
          enableCustomDeployment: true
          DeploymentType: 'zipDeploy'
          JSONFiles: '**/appsettings.json'

```
