### ISSUE TITLE
umbraco folder missing when running dotnet publish

### ISSUE THREAD

**Issue by SteveVaneeckhout** [umbraco/Umbraco-CMS#11203]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc004

### Bug summary

When running the command `dotnet publish --output PublishDir` the `umbraco` folder in the root of PublishDir is missing. The deployed website will not have a working backoffice.

### Specifics

I'm using .NET Core 5 - No beta's of .NET Core 6 or VS installed.

### Steps to reproduce

Open a commandline and run
```
mkdir umbraco9test
cd umbraco9test
dotnet new umbraco
dotnet publish --output publish
```

Notice the `publish` directory doesn't contain the umbraco folder.

### Expected result / actual result

The umbraco folder should be there.

I asked this question on [the forum](https://our.umbraco.com/forum/umbraco-9/107173-missing-umbraco-folder-after-dotnet-publish-900-rc004) and Søren responded with: run `dotnet build` before publish. This works on my machine but not in my Azure DevOps pipeline where I get the error:

```
error NETSDK1022: Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default.
You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file.
For more information, see https://aka.ms/sdkimplicititems.

The duplicate items were:
'umbraco\PartialViewMacros\Templates\Breadcrumb.cshtml';
'umbraco\PartialViewMacros\Templates\EditProfile.cshtml';
'umbraco\PartialViewMacros\Templates\Empty.cshtml';
'umbraco\PartialViewMacros\Templates\Gallery.cshtml';
'umbraco\PartialViewMacros\Templates\ListAncestorsFromCurrentPage.cshtml';
'umbraco\PartialViewMacros\Templates\ListChildPagesFromChangeableSource.cshtml';
'umbraco\PartialViewMacros\Templates\ListChildPagesFromCurrentPage.cshtml';
'umbraco\PartialViewMacros\Templates\ListChildPagesOrderedByDate.cshtml';
'umbraco\PartialViewMacros\Templates\ListChildPagesOrderedByName.cshtml';
'umbraco\PartialViewMacros\Templates\ListChildPagesOrderedByProperty.cshtml';
'umbraco\PartialViewMacros\Templates\ListChildPagesWithDoctype.cshtml';
'umbraco\PartialViewMacros\Templates\ListDescendantsFromCurrentPage.cshtml';
'umbraco\PartialViewMacros\Templates\ListImagesFromMediaFolder.cshtml';
'umbraco\PartialViewMacros\Templates\Login.cshtml';
'umbraco\PartialViewMacros\Templates\LoginStatus.cshtml';
'umbraco\PartialViewMacros\Templates\MultinodeTree-picker.cshtml';
'umbraco\PartialViewMacros\Templates\Navigation.cshtml';
'umbraco\PartialViewMacros\Templates\RegisterMember.cshtml';
'umbraco\PartialViewMacros\Templates\SiteMap.cshtml';
'umbraco\UmbracoBackOffice\AuthorizeUpgrade.cshtml';
'umbraco\UmbracoBackOffice\Default.cshtml';
'umbraco\UmbracoBackOffice\Preview.cshtml';
'umbraco\UmbracoInstall\Index.cshtml';
'umbraco\UmbracoWebsite\NoNodes.cshtml';
'umbraco\config\appsettings-schema.json'
```

This _might_ be a different issue that can be solved by adding `<EnableDefaultContentItems>false</EnableDefaultContentItems>` here: https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/build/NuSpecs/build/Umbraco.Cms.StaticAssets.targets#L3

**Comment by bergmania** [comment]
You will need to do a build explictly before you publish.

```
mkdir umbraco9test
cd umbraco9test
dotnet new umbraco
dotnet build
dotnet publish --output publish
```

**Comment by SteveVaneeckhout** [comment]
That works locally but not in my pipeline. The second command (dotnet publish) throws error NETSDK1022.
This is the YAML File:
```
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  SolutionPath: 'UmbLinTest.sln'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(SolutionPath)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(SolutionPath)'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
```
