### ISSUE TITLE
Getting corrupted tarball data for @umbraco-cms/backoffice v15.1.1

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#17850]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1.1

### Bug summary

I am building a package.json with a reference to the latest backoffice version (15.1.1)
On my local machine, `npm i` runs without incidents
On an Azure Devops pipeline, the same command aborts with this error:
```
tarball data for @umbraco-cms/backoffice@https://registry.npmjs.org/@umbraco-cms/backoffice/-/backoffice-15.1.1.tgz (sha512-Aoy/lFLXDxRIWYF5cM4YNTM7CRdSRbKE463271IXpvyLJUa0xg9pSdrKwsw+i0/YySDSnvXgwQ63WBKN3IJFtQ==) seems to be corrupted
```

### Specifics

The default `registry.npmjs.org` is used - should I include a nuget.config to use a different registry?

### Steps to reproduce

Include these dependencies in package.json
```
  "devDependencies": {
    "@hey-api/openapi-ts": "^0.57.1",
    "@umbraco-cms/backoffice": "^15.1.1",
    "typescript": "^5.7.2",
    "vite": "^5.4.11"
  }
```
and try to run `npm i` in an AzureDevops pipeline, i.e:
```
  - task: UseNode@1
    displayName: Use Node 20.11.0
    inputs:
      version: 20.11.0
  - script: npm i
    displayName: 'npm install dependencies'      
    workingDirectory: .\src\my-project
```
