### ISSUE TITLE
Unable to add content to NC used in DTGE when copied item

### ISSUE THREAD

**Issue by stefankip** [umbraco/Umbraco-CMS#7918]
I have the DataType Grid Editor in use and one of the elements I can add uses a Nested Content property.
This works fine, but when I copy a NC item and try to add an item to NC, the dialog to choose between pasting and creating an item is not visible in the viewport.
If I remove the `position: fixed` property of the `.umb-overlay` class, the dialog is shown again:

![image](https://user-images.githubusercontent.com/46313552/78885136-5a5f5b00-7a5c-11ea-979b-d961143dfb8e.png)

This is with umbraco v8.6.0 and latest DTGE.

**Comment by enkelmedia** [comment]
When I looked in to this it turns out that is the umb-overlay is used inside a view from the editor service it gets miss-placed, I fiddled for a while but ended up with a little CSS-override that would place the overlay to the right. I can't share any screenshots from that solution but this less might helt out.

```css
// Fix for umb-overlay inside a EditorService-dialog.
.umb-editors {
    .umb-overlay {
        //position: absolute !important;
        // To the left
        left: inherit !important;
        right: 0 !important;
        top: 0 !important;
        bottom: 0 !important;
    }
}
```

As far as I understand the umb-overlay is obsolete so maybe this is a ok fix to ship in the core. We're using it in a solution right now (not any language variants) and it works very well.

Hope it helps.
