### ISSUE TITLE
Block action is inherting css it shouldn't

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#8872]
![image](https://user-images.githubusercontent.com/3726467/92919312-8a0df700-f430-11ea-8f2a-252c347871dd.png)

The action bar at the right looks wrong. the icons are too big, and there is a right margin on each of them making it look broken.

I think this comes from this css, responsible for styling the icon to the left of the label in the default block preview:
```css
.blockelement-labelblock-editor i {
    font-size: 22px;
    margin-right: 5px;
    display: inline-block;
    vertical-align: middle;
}
```

I'm only getting this, because I'm doing this [Block List in Block List approach for making a grid](https://twitter.com/skttl/status/1303675858494861312), which puts the action bar inside a `.blockelement-labelblock-editor`.

A simple fix is to change the selector to `.blockelement-labelblock-editor > i`

Version 8.7.0
