### ISSUE TITLE
Default block preview doesn't handle text overflow well

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#8876]
The default block preview kind of breaks, when the text-label exceeds the available space.
![image](https://user-images.githubusercontent.com/3726467/92925258-83847d00-f43a-11ea-8da0-e3d95d5a5c79.png)

Can be fixed by adding the following css:

```css
.blockelement-labelblock-editor {
display:flex;
padding:12px 20px;
}
.blockelement-labelblock-editor i {
margin-right:10px;
}
.blockelement-labelblock-editor span {
padding-top:2px;
padding-bottom:2px;
}
```

Then it looks like this:
![image](https://user-images.githubusercontent.com/3726467/92925585-ff7ec500-f43a-11ea-9329-c5d1b06752d9.png)
