### ISSUE TITLE
Netcore: Split monolith test projects

### ISSUE THREAD

**Issue by p-m-j** [umbraco/Umbraco-CMS#9396]
The Umbraco.Tests.UnitTests project tests 8 libraries, the tests are grouped by namespace so there is an Umbraco.Web.Common folder which has all the tests for Umbraco.Web.Common.

It would be much nicer if there were more test projects with less broad a focus.

This applies to both unit/integration tests.

Goals
1. Create more tests projects e.g. Umbraco.Web.Common.Tests.UnitTests
1. Create these test projects under tests/ instead of src/
1. Autodiscover test projects in the CI build such that adding a new test project to tests/ results in tests being run.

@JimBobSquarePants did I miss anything here?

**Comment by rustybox** [comment]
Bonus points for yaml build definition so community have visibility of the CI build?

**Comment by rustybox** [comment]
At present this requires the assistance from staff with permissions to edit the build pipeline on azure devops as the dotnet test step is explicit about which projects it runs.

Apparently one can now just run dotnet test against the sln file, so no need to manually discover csproj under tests/ anymore.

**Comment by JimBobSquarePants** [comment]
You can run `dotnet test` against [a folder](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#arguments), doesn't even need to be a solution file.  

Put yes, I would advocate splitting up tests. Current `InternalsVisibleTo` rules would need to be updated but that's trivial and can be configured in single `Directory.Build.props/targets` files.

Those yaml files should definitely be public.

**Comment by rustybox** [comment]
It's classic builds atm as opposed to yaml as far as I can tell.

**Comment by rustybox** [comment]
Went to check, you can pass a path to a folder containing a sln or a csproj, you can't just pass a path to a folder with multiple test project folders underneath there's no recursion.

**Comment by bergmania** [comment]
We would like the build to be YAML, but does not have time to look into it yet. 

Some things to note:
- We would like the unit tests to be executed on both a Windows agent and a Linux agent
- Integration tests should only run on Windows (Due to the LocalDB dependency)

Regarding the test projects, I'm pretty sure you can use `*` as wildcard, so it could be something like `*.UnitTests.csproj` for unit tests and `*.IntegrationTests.csproj`

**Comment by rustybox** [comment]
not on a path no

```bash
dotnet test tests\**\*.csproj
```

This isn't a thing as much as i'd like it to be.

```bash
dotnet test umbraco.sln 
```

Does everything we need though.

**Comment by bergmania** [comment]
Today our step in Azure looks like this in YAML. 
```
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: |
     **\Umbraco.Tests.UnitTests.csproj
     **\Umbraco.Tests.Integration.csproj
```

So I'm pretty sure the test command in azure devops support the wildcards, even that the `dotnet test` command maybe doesn't

Do we still have an easy way to run all unit tests on each build / Live unittesting / Continuous testing, if we separate the test projects into many?

**Comment by rustybox** [comment]
> Do we still have an easy way to run all unit tests on each build / Live unittesting / Continuous testing, if we separate the test projects into many?

If this works then yes

```
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: |
     **\*.UnitTests.csproj
     **\*.Integration.csproj
```
